### ISSUE TITLE
[shell] bash対応

### ISSUE THREAD

**Issue by yamamoto-yuta** [Fuzzy-Explorer/Fuzzy-Explorer-on-Terminal#25]

**Comment by yamamoto-yuta** [comment]
Dockerのコンテナ内で使えたらとても助かる…

**Comment by ShotaroKataoka** [comment]
@yamamoto-yuta 
zsh依存の部分を洗い出す必要がある
bashで実行してみてどこが詰まるか確認するか

頼めますか？？

**Comment by yamamoto-yuta** [comment]
@ShotaroKataoka 
ついでにインストール時の遺存周りも調べてみます

**Comment by ShotaroKataoka** [comment]
@yamamoto-yuta 
ありがとう！！

**Comment by ShotaroKataoka** [comment]
@yamamoto-yuta 
richcatは `pip install richcat` で多分入ると思います！

**Comment by ShotaroKataoka** [comment]
@yamamoto-yuta 
[richcat](https://pypi.org/project/richcat/)
これっすね

**Comment by yamamoto-yuta** [comment]
ひとまず `wsl_explorer.zsh` → `.bashrc` にファイル名を変更して実行してみたところ，以下のエラーが出ました．
```
bash: /home/.bashrc: line 33: syntax error near unexpected token `;'
bash: /home/.bashrc: line 33: `    else;'
```

**Comment by yamamoto-yuta** [comment]
bashだと `else` の後に `;` があるとエラーが吐かれるようです．

**Comment by ShotaroKataoka** [comment]
ぽいね．．．

**Comment by ShotaroKataoka** [comment]
```
if [ 条件 ]; then
else
    処理
fi
```
はifのあとに何もないので怒られる

:（コロン）を置いとけば通る（何もしないコマンド）

**Comment by yamamoto-yuta** [comment]
エラー出ました
```
bash: .bashrc: line 149: syntax error near unexpected token `{}'
bash: .bashrc: line 149: `  function chpwd() {}'
```

**Comment by ShotaroKataoka** [comment]
```
function chpwd() {
  :
}
```

**Comment by yamamoto-yuta** [comment]
```
echo -e "$_wsl_explorer_var_dir_list"
```

**Comment by yamamoto-yuta** [comment]
```
--layout=reverse
```

**Comment by yamamoto-yuta** [comment]
ディレクトリ移動すると怒られました．
```
bash: [: =: unary operator expected
```

**Comment by yamamoto-yuta** [comment]
一部キーバインドが効かない・想定通りの動作をしない（例外として `alt + a` は適切に動作する）

**Comment by ShotaroKataoka** [comment]
ステータスの条件分岐に引っかかってないっぽい
hiddenは効く

**Comment by ShotaroKataoka** [comment]
あとたぶん入力系のvaredでエラー起こる

**Comment by ShotaroKataoka** [comment]
@yamamoto-yuta 
ひとまずここまで判明した内容でdevelopをbash対応させてみます

**Comment by ShotaroKataoka** [comment]
`echo $0`でbashかzshか判別できる．なんかfishはだめらしい．知らんけど

**Comment by ShotaroKataoka** [comment]
zshとbashで配列の動作が違う
zshは1から始まるが，bashは0から始まる
配列の要素を取得する関数を作るか，zshにsetoptで0から始まるようにするかをする

**Comment by ShotaroKataoka** [comment]
- シバン
- local削除
- setopt削除
- else;のセミコロン削除
- if-elseでifが空処理のときコロンを挿入
- if-elifも同様
- echo -e "$_fet_path_path_list" (-eとダブルクォーテーションが重要)
- font awesomeが解釈されない
- ANSIがなぜか効かない
- https://github.com/Fuzzy-Explorer/Fuzzy-Explorer-on-Terminal/issues/25#issuecomment-728133322
- 配列のforは${array[@]}で回す
- `_aaa_$var='aaaa'`みたいに変数名の途中に変数を使う場合`eval aaa_$var='aaaa'`とする
- `for var in $(seq 0 $(expr ${#_fet_plugins_status_list[*]} - 1))` 0から要素数-1までにする
- redocdなど：配列の要素削除にunsetが使える
- redocdなど：`$(expr $following_dirs_num - 1)` 配列の末尾の要素の番号

- QuickAccessとwindows jumpはまだ非対応

**Comment by ShotaroKataoka** [comment]
@yamamoto-yuta 
bashでもかなり動くようになった
