### ISSUE TITLE
[recent access] RecentAccess機能

### ISSUE THREAD

**Issue by yamamoto-yuta** [Fuzzy-Explorer/Fuzzy-Explorer-on-Terminal#3]
既存のvim-recent機能とdirectory-history機能をWSL-Explorer上で実現したい

**Comment by ShotaroKataoka** [comment]
@yamamoto-yuta 
vimのラッパー問題が解決し次第実装したい
あとはdirectory-historyはzshしか動かない
ちなvirと同じ仕組みでcdをラップしちゃえば多分bash上でも実装できる

**Comment by ShotaroKataoka** [comment]
`.vir-recent` と統合してもいい
とりあえずvimしたのもcdしたのも全部recentにいれといて
`vir` ではファイルのみ，`fdh`ではディレクトリのみでgrepする
recent accessでは全部列挙するけどディレクトリとファイルで表示と動作を変える

タイムスタンプとってないけどこれならrecent access上での並び順がいい感じになる
