### ISSUE TITLE
[install] インストールを簡単にできるようにする

### ISSUE THREAD

**Issue by ShotaroKataoka** [Fuzzy-Explorer/Fuzzy-Explorer-on-Terminal#6]
必要な環境なども調査する

**Comment by ShotaroKataoka** [comment]
dpkgでパッケージングする

**Comment by ShotaroKataoka** [comment]
@yamamoto-yuta 
bash対応ブランチで`install`を作成してみました

**Comment by yamamoto-yuta** [comment]
@ShotaroKataoka 
.fetディレクトリが無いと怒られました

**Comment by ShotaroKataoka** [comment]
@yamamoto-yuta 
あ、ごめん
fzfみたいにインストールするからコマンドがいる
READMEかいてプルリクします！
