### ISSUE TITLE
Backspaceで親ディレクトリに戻らないようにしたい

### ISSUE THREAD

**Issue by yamamoto-yuta** [Fuzzy-Explorer/Fuzzy-Explorer-on-Terminal#64]
曖昧検索したキーワードをBackspaceで削除してたら，Backspace押しすぎて親ディレクトリに遷移してしまうことが良くあったので…

**Comment by ShotaroKataoka** [comment]
@yamamoto-yuta 
config.zshでbackward-eofをコメントしてbuildしてみて

これデフォルトでオフにしとくか
