### ISSUE TITLE
fetコマンドを実行したディレクトリに即戻れる機能が欲しい

### ISSUE THREAD

**Issue by yamamoto-yuta** [Fuzzy-Explorer/Fuzzy-Explorer-on-Terminal#68]
「あのディレクトリどうなってたっけ？」とか「このディレクトリでエクスプローラ起動したい」等，そのディレクトリに移動したいわけじゃなくて確認したいだけのときに，サクッと戻れたら便利かも，と思いました．

**Comment by ShotaroKataoka** [comment]
previous_listの最初の要素は絶対実行時dirのはずなので実装は簡単そう
pluginで対応してもいいけどどうかな

**Comment by yamamoto-yuta** [comment]
@ShotaroKataoka 
previous_listってどこに書いてありますか？

**Comment by ShotaroKataoka** [comment]
funtion/undocdとかで操作してる変数
グローバル変数なのでどこからでも参照できる

**Comment by yamamoto-yuta** [comment]
@ShotaroKataoka 
`_fet_path_previous_dirs` で合ってますか？

**Comment by ShotaroKataoka** [comment]
@yamamoto-yuta 
それ

**Comment by yamamoto-yuta** [comment]
@ShotaroKataoka 
pluginで作ってみます！

**Comment by ShotaroKataoka** [comment]
神っす！
